%YAML 1.2
---
    
training:
    batch_size: 512                    # training batch
    checkpoint_steps: 1000             # optional frequency for checkpointing before finish
    train_avg_report_steps: 500        # training reports its average values after this many steps.
    shuffle_size: 50000               # size of the shuffle buffer
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    moves_left_loss_weight: .01
    swa: false                         # Stochastic Weight Average
    swa_max_n: 0                       # Stochastic Weight Average Max
    precision: single
    loss_scale: 128

    renorm: false
    renorm_max_r: 1
    renorm_max_d: 0
    renorm_momentum: 0.99

    q_ratio: 0



